package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Config holds releasebot configuration from .releasebot.yml.
type Config struct {
	// Justfile holds settings for running just recipes.
	Justfile *JustfileConfig `yaml:"justfile"`
	// Changelog holds changelog generation settings.
	Changelog *ChangelogConfig `yaml:"changelog"`
	// GitHub holds optional GitHub API settings for fetching PRs.
	GitHub *GitHubConfig `yaml:"github"`
	// LLM at top level (optional). Used when changelog.llm is not set. Lets you enable LLM with only "llm:" in config.
	LLM *LLMConfig `yaml:"llm"`
	// PreviousReleaseTag can be set in config (overridden by --prev-tag).
	PreviousReleaseTag string `yaml:"previous_release_tag"`
	// Release holds settings for the release command (remote, pypi, docker).
	Release *ReleaseConfig `yaml:"release"`
	// Slack holds optional Slack notification (e.g. when run completes).
	Slack *SlackConfig `yaml:"slack"`
}

// SlackConfig configures Slack notifications (e.g. on run completion).
// WebhookURL can be set in config or via SLACK_WEBHOOK_URL env.
type SlackConfig struct {
	// WebhookURL is the Slack Incoming Webhook URL. If empty, SLACK_WEBHOOK_URL is used.
	WebhookURL string `yaml:"webhook_url"`
}

// ReleaseConfig configures the release command (push remote, and optional PyPI/Docker wait).
type ReleaseConfig struct {
	// Remote is the git remote to push branch and tags to (default: origin).
	Remote string `yaml:"remote"`
	// PyPIPackage is the PyPI package name to check/wait for after release (e.g. my-package). If set, release waits for package==version on PyPI.
	PyPIPackage string `yaml:"pypi_package"`
	// DockerImage is the Docker image to check/wait for (e.g. myorg/myimage). If set, release waits for myorg/myimage:tag on Docker Hub.
	DockerImage string `yaml:"docker_image"`
}

// JustfileConfig configures execution of justfile recipes.
type JustfileConfig struct {
	// Targets is the list of just recipe names to run in order.
	Targets []string `yaml:"targets"`
	// WorkingDir is the directory containing the justfile (default: repo root).
	WorkingDir string `yaml:"working_dir"`
}

// ChangelogConfig configures changelog generation.
type ChangelogConfig struct {
	// Output path for the changelog file (default: CHANGELOG.md).
	Output string `yaml:"output"`
	// UseHistory, when true, uses git commit history for the changelog instead of PRs. Overridden by --use-history.
	UseHistory *bool `yaml:"use_history"`
	// UsePRs, when true, uses merged GitHub PRs for the changelog. Requires github.enabled. Overridden by --use-prs.
	UsePRs *bool `yaml:"use_prs"`
	// Format is a template or instructions for how each entry should look (used when not summarize_per_pr).
	Format string `yaml:"format"`
	// FormatFile path to a file containing the format template (overrides Format if set).
	FormatFile string `yaml:"format_file"`
	// Template is the changelog writer template (Go text/template) when using summarize_per_pr.
	// Sections are in .Sections (e.g. .Sections.Added). Each entry has .Description, .PRID, .URL.
	// Can be multiline YAML (use | or >).
	Template string `yaml:"template"`
	// TemplateFile path to a file containing the changelog template (overrides Template if set).
	TemplateFile string `yaml:"template_file"`
	// LLM config (optional). When set, changelog section is generated by an LLM.
	LLM *LLMConfig `yaml:"llm"`
}

// LLMConfig configures the LLM used for changelog generation.
type LLMConfig struct {
	// Provider is "openai", "ollama", or "anthropic". Can also be set via RELEASEBOT_LLM_PROVIDER.
	Provider string `yaml:"provider"`
	// Model name (e.g. gpt-4o-mini for OpenAI, llama3.2 for Ollama, claude-sonnet-4-5-20250929 for Anthropic).
	Model string `yaml:"model"`
	// BaseURL overrides the API base URL (optional for OpenAI; for Ollama default is http://localhost:11434/v1).
	BaseURL string `yaml:"base_url"`
	// SummarizePerPR: when true, analyze each PR independently (LLM → JSON per PR), then build the final
	// changelog from that JSON. When false, feed the LLM all PRs at once (single call; more context, may be slower).
	SummarizePerPR bool `yaml:"summarize_per_pr"`
	// IncludeDiff: when SummarizePerPR is true, pass the PR diff to the LLM (in addition to title/body). Expensive and token-heavy.
	IncludeDiff bool `yaml:"include_diff"`
	// CacheLLMSummaries: when SummarizePerPR is true, cache each PR's LLM summary (default true).
	CacheLLMSummaries *bool `yaml:"cache_llm_summaries"`
}

// GitHubConfig configures optional GitHub API usage.
type GitHubConfig struct {
	// Enabled turns on fetching merged PRs between tags (default: false).
	Enabled bool `yaml:"enabled"`
	// Token is the GitHub token (prefer GITHUB_TOKEN env; set here for override).
	Token string `yaml:"token"`
	// Owner and Repo override git remote; if empty, derived from origin.
	Owner string `yaml:"owner"`
	Repo  string `yaml:"repo"`
}

// Load reads config from path. If the file does not exist, returns default config and nil error.
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Config{}, nil
		}
		return nil, fmt.Errorf("read config: %w", err)
	}
	var c Config
	if err := yaml.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	return &c, nil
}

// Resolve resolves paths relative to repoRoot.
func (c *Config) Resolve(repoRoot string) {
	if c.Changelog != nil && c.Changelog.Output == "" {
		c.Changelog.Output = "CHANGELOG.md"
	}
	if c.Justfile != nil && c.Justfile.WorkingDir != "" && !filepath.IsAbs(c.Justfile.WorkingDir) {
		c.Justfile.WorkingDir = filepath.Join(repoRoot, c.Justfile.WorkingDir)
	}
}

// ChangelogFormat returns the changelog entry format string (from Format or FormatFile).
func (c *Config) ChangelogFormat(repoRoot string) (string, error) {
	if c.Changelog == nil {
		return "- {{.Title}} (#{{.Number}})", nil
	}
	if c.Changelog.FormatFile != "" {
		path := c.Changelog.FormatFile
		if !filepath.IsAbs(path) {
			path = filepath.Join(repoRoot, path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return "", fmt.Errorf("read format file: %w", err)
		}
		return string(data), nil
	}
	if c.Changelog.Format != "" {
		return c.Changelog.Format, nil
	}
	return "- {{.Title}} (#{{.Number}})", nil
}

// ChangelogTemplate returns the changelog writer template (for summarize_per_pr). Uses TemplateFile, then Template, then default.
func (c *Config) ChangelogTemplate(repoRoot string) (string, error) {
	if c.Changelog == nil {
		return defaultChangelogTemplate, nil
	}
	if c.Changelog.TemplateFile != "" {
		path := c.Changelog.TemplateFile
		if !filepath.IsAbs(path) {
			path = filepath.Join(repoRoot, path)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return "", fmt.Errorf("read template file: %w", err)
		}
		return string(data), nil
	}
	if c.Changelog.Template != "" {
		return c.Changelog.Template, nil
	}
	return defaultChangelogTemplate, nil
}

// defaultChangelogTemplate is used as the structure/format passed to the LLM when generating the changelog from summarized records (describe version heading, sections by change type, and entry format).
const defaultChangelogTemplate = `## {{.Version}}
{{range $section := .SectionOrder}}{{if index $.Sections $section}}
### {{$section}}
{{range index $.Sections $section}}
- {{.Description}} [#{{.PRID}}]({{.URL}})
{{end}}
{{end}}{{end}}
`
